export const OrderData =[
    {key: 1, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'none', status: 'New Order', statusColor: '#FFB74A', nextStatus: 'Accept', nextStatusColor: '#43D636'},
    {key: 2, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'notice color shirt and white shirt', status: 'New Order', statusColor: '#FFB74A', nextStatus: 'Accept', nextStatusColor: '#43D636'},
    {key: 3, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'do not use laundry machine for jean', status: 'Accept', statusColor: '#43D636', nextStatus: 'Processing', nextStatusColor: '#6AB8FF'},
    {key: 4, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'do not use laundry machine for jean', status: 'Processing', statusColor: '#6AB8FF', nextStatus: 'Finish', nextStatusColor: '#FFC700'},
    {key: 5, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'do not use laundry machine for jean', status: 'Accept', statusColor: '#43D636', nextStatus: 'Processing', nextStatusColor: '#6AB8FF'},
    {key: 6, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'do not use laundry machine for jean', status: 'Processing', statusColor: '#6AB8FF', nextStatus: 'Finish', nextStatusColor: '#FFC700'},
    {key: 7, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'none', status: 'Finish', statusColor: '#FFC700', nextStatus: 'Nothing at all', nextStatusColor: '#43D636'},
    {key: 8, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'notice color shirt and white shirt', status: 'New Order', statusColor: '#FFB74A', nextStatus: 'Accept', nextStatusColor: '#43D636'},
    {key: 9, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'do not use laundry machine for jean', status: 'Accept', statusColor: '#43D636', nextStatus: 'Processing', nextStatusColor: '#6AB8FF'},
    {key: 10, service: 'Standard Laundry', price: '15.000', weight:'5', orderAt: '13:00', finishAt: '', note: 'do not use laundry machine for jean', status: 'Processing', statusColor: '#6AB8FF', nextStatus: 'Finish', nextStatusColor: '#FFC700'},
];
